version: "3.3"
    
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: thmpv005
      MYSQL_DATABASE: estoque
      MYSQL_USER: michel
      MYSQL_PASSWORD: michel
    command: ['mysqld', '--default-time-zone=-03:00']
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3306:3306"
