version: "3.3"
    
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: thmpv005
      MYSQL_DATABASE: estoque
      MYSQL_USER: michel
      MYSQL_PASSWORD: michel
    ports:
      - "3306:3306"
