spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: thmpv005
    url: jdbc:mysql://127.0.0.1:3306/estoque
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate